baseURL = 'https://www.prenderlink.net/'
languageCode = 'en-us'
title = 'Prenderlink'
theme = "archie"

[params]
  subtitle = "Hello! I sometimes write articles or make videos about something cool I've learned and want to share. Stay tuned!"

# Menu
[menu]
  main = [
    
    { name = "Blogs", url = "/blog/" },
    { name = "About", url = "/about/" },  
    
  ]

# Github Pages
[deployments]
  githubPages = { enabled = true }
